agrego un diseño amigable para el pdf
teamcubation/byma-financial-report pull request #15
Opened 2024-10-24 04:10 UTC by MrChax

…der a primera vistalo que se quiere mostrar

2024-10-24 13:00 UTC, DamianMarquezMeli requested changes

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        com.lowagie.text.Font titleFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 16, com.lowagie.text.Font.BOLD, Color.BLACK);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        com.lowagie.text.Font tableHeaderFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 12, com.lowagie.text.Font.BOLD, Color.WHITE);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        com.lowagie.text.Font tableBodyFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.NORMAL, Color.BLACK);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        titleBonds.setSpacingAfter(10);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        PdfPTable bondTable = new PdfPTable(4);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        bondTable.setWidthPercentage(100);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        PdfPTable stockTable = new PdfPTable(4);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        stockTable.setWidthPercentage(100);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        Paragraph titleBonds = new Paragraph("Lista de Bonos", titleFont);
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        addTableHeader(bondTable, "ID", "Nombre", "Precio", "Tasa de Interés", tableHeaderFont);
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        document.add(new Paragraph("\n"));
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        Paragraph titleStocks = new Paragraph("Lista de Acciones", titleFont);
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        titleStocks.setSpacingAfter(10);
numero magico, no deberia de estar permitido

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        com.lowagie.text.Font titleFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 16, com.lowagie.text.Font.BOLD, Color.BLACK);
El caso de si es bold o black, se podria crear las constantes para no recrear bastnate la informacion y lo mejor es no ir instanciando en cada llamada.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        com.lowagie.text.Font tableHeaderFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 12, com.lowagie.text.Font.BOLD, Color.WHITE);
El caso de si es bold o black, se podria crear las constantes para no recrear bastnate la informacion y lo mejor es no ir instanciando en cada llamada.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        titleBonds.setAlignment(Element.ALIGN_CENTER);
El caso de si es bold o black, se podria crear las constantes para no recrear bastnate la informacion y lo mejor es no ir instanciando en cada llamada.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        titleStocks.setAlignment(Element.ALIGN_CENTER);
El caso de si es bold o black, se podria crear las constantes para no recrear bastnate la informacion y lo mejor es no ir instanciando en cada llamada.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +        addTableHeader(stockTable, "ID", "Nombre", "Precio", "Dividendo (%)", tableHeaderFont);
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +            stockTable.addCell(new PdfPCell(new Phrase(String.valueOf(stock.getDividend()) + "%", tableBodyFont)));
String hardcode no deberia de estar, se deberia de crear una constante para comprendr bien la funcion.

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +    private static void addTableHeader(PdfPTable table, String col1, String col2, String col3, String col4, com.lowagie.text.Font headerFont) {
Los nombres de los parámetros no son claros

2024-10-24 13:00 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
> +    private static void addTableHeader(PdfPTable table, String col1, String col2, String col3, String col4, com.lowagie.text.Font headerFont) {
no se valida si ha datos nulls en los parametros, eso es un posible error a futuro.

2024-10-29 17:53 UTC, DamianMarquezMeli approved these changes, later dismissed

2024-10-29 19:20 UTC, julianmarcelolopez requested changes
Heber, agrego 2 comentarios.

2024-10-29 19:20 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/generatorfile/GeneratorPdf.java
> +        addTableHeader(stockTable, "ID", "Nombre", "Precio", "Dividendo (%)");
Estas leyendas tambien se podrian pasar a constantes.

2024-10-29 19:20 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/generatorfile/GeneratorPdf.java
> +        addTableHeader(bondTable, "ID", "Nombre", "Precio", "Tasa de Interés");
Estas leyendas tambien se podrian pasar a constantes.

2024-10-29 20:01 UTC, DamianMarquezMeli submitted a review, later dismissed

2024-10-29 21:33 UTC, julianmarcelolopez approved these changes
Ok

2024-10-29 23:06 UTC, merged