actualizado el http filter chain e incorporado endpoint de actualizac…
teamcubation/byma-financial-report pull request #23
Opened 2024-10-28 17:19 UTC by Tavo-94

2024-10-28 17:41 UTC, julianmarcelolopez requested changes
Gus, te dejo algunos comentarios.

2024-10-28 17:41 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
> +    public ResponseEntity<UserResponse> updateRegularUser(@PathVariable long id, @RequestBody UserUpdateRequestDTO userRequest) throws Exception {
Aca se deberia individualizar la exception y no lanzar una exception generica.

2024-10-28 17:41 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
> +    public ResponseEntity<UserResponse> updateRegularUser(@PathVariable long id, @RequestBody UserUpdateRequestDTO userRequest) throws Exception {
Este RequestBody entiendo que deberia ser requerido y validarlo en caso que algun campo venga nulo.

2024-10-28 17:41 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
> +        user.setId(id);
Entiendo que el id tambien se lo podria enviar al Mapper.

2024-10-28 17:41 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
> +        Assert.notNull(userUpdateRequestDTO, "UserUpdateRequestDTO cannot be null");
Validar que estamos manejando correctamente esta excepcion.

2024-10-28 17:50 UTC, DamianMarquezMeli requested changes

2024-10-28 17:50 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
> +    }
El ASSERT es solamente para TEST. Para utilizarlo en modo que no sea local se tienne que hacer configuraciones en la inicializacion de la aplicacion para que entre en un modo especial que utilice el Assert.

eliminar el Assert y hacer la validacion de otra forma.

2024-10-28 17:50 UTC, DamianMarquezMeli commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserUpdateRequestDTO.java
> +    public String username;
Utilizar Camel Case para el nombre del atributo

2024-10-29 15:04 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
> +    public ResponseEntity<UserResponse> updateRegularUser(@PathVariable long id, @RequestBody UserUpdateRequestDTO userRequest) throws Exception {
Agregue la validacion de un request body nulo, la validacion por campos esta en el service.

2024-10-29 17:47 UTC, julianmarcelolopez requested changes
Gus, te dejo algunos comentarios mas de algunas cosas que veo que surgieron ahora.

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        throw new RuntimeException(USER_NOT_AUTHENTICATED);
Deberia ser una excepcion personalizada, ej: UserNotAuthenticatedException

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        String userEmail = getAuthenticatedUserEmail();
si la variable va a tener un solo uso, directamente en la linea de abajo llama al metodo getAuthenticatedUserEmail().

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        if (typeInstrument == null) {
Todo este if lo encapsularia en un metodo privado que devuelva downloadUrls y lo invicaria directamente en la linea: 
savedReport.setDownloadUrl(getDownloadUrls());

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +            throw new RuntimeException(REPORT_NOT_FOUND);
Esta tambien deberia ser una excepcion personalizada.

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +            log.warn(REPORT_NOT_FOUND);
Este log entiendo que seria un log.error

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        log.warn(INSTRUMENT_TYPE_NOT_SUPPORTED);
log.error tambien seria.

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        return getReportsByUserEmail(userEmail);
Lo resumiria en una sola linea.

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
> +                        throw new RuntimeException("Failed to convert User to UserResponse", e);
Agreguemos una exception personalizada y log.error()

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapter.java
> +                        throw new RuntimeException("Failed to convert UserEntity to User",e);
Deberia de ser una exception personalizada.

2024-10-29 17:47 UTC, julianmarcelolopez commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
> +                        throw new RuntimeException("Failed to convert UserEntity to User", e);
Aca lo mismo, debiera ser una excepcion personalizada.

2024-10-29 18:11 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        throw new RuntimeException(USER_NOT_AUTHENTICATED);
ya esta siendo tratado en [https://github.com/teamcubation/byma-financial-report/tree/feature/testing-service-report](url)

2024-10-29 18:11 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        String userEmail = getAuthenticatedUserEmail();
ya esta siendo tratado en otra feature

2024-10-29 18:11 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +            throw new RuntimeException(REPORT_NOT_FOUND);
ya esta siendo tratado en [https://github.com/teamcubation/byma-financial-report/tree/feature/testing-service-report](url)

2024-10-29 18:12 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +            log.warn(REPORT_NOT_FOUND);
ya esta siendo tratado en [https://github.com/teamcubation/byma-financial-report/tree/feature/testing-service-report](url)

2024-10-29 18:12 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        log.warn(INSTRUMENT_TYPE_NOT_SUPPORTED);
ya esta siendo tratado en [https://github.com/teamcubation/byma-financial-report/tree/feature/testing-service-report](url)

2024-10-29 18:12 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        return getReportsByUserEmail(userEmail);
ya esta siendo tratado en [https://github.com/teamcubation/byma-financial-report/tree/feature/testing-service-report](url)

2024-10-29 18:13 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
> +        if (typeInstrument == null) {
ya esta siendo tratado en otra feature

2024-10-29 18:34 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
> +                        throw new RuntimeException("Failed to convert User to UserResponse", e);
corregido

2024-10-29 18:34 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapter.java
> +                        throw new RuntimeException("Failed to convert UserEntity to User",e);
corregido

2024-10-29 18:35 UTC, Tavo-94 commented on src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
> +                        throw new RuntimeException("Failed to convert UserEntity to User", e);
corregido

2024-10-29 19:09 UTC, julianmarcelolopez approved these changes
Buenisimo.

2024-10-29 19:50 UTC, DamianMarquezMeli approved these changes

2024-10-29 19:55 UTC, merged